Refactor compose.sh to be reused better.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -55,6 +55,12 @@ ip=$(ping -c 1 ${SERVER_HOSTNAME} | awk -F '[()]' '/PING/{print $2}')
 # How to silence curl: https://unix.stackexchange.com/questions/196549/hide-curl-output
 echo url="https://www.duckdns.org/update?domains=${DUCKNS_SUBDOMAIN}&token=${DUCKDNS_TOKEN}&ip=${ip}" | curl -s -K - > /dev/null
 
-generate_secrets "$(get_compose)"
+COMPLETE_COMPOSE=$(get_compose)
+if [[ "$COMPLETE_COMPOSE" == "" ]]; then
+    >&2 echo "There was an error generating the compose file. Exiting."
+    exit 1;
+fi
 
-get_compose | docker stack deploy --compose-file - ${STACK_NAME:-technocore}
+generate_secrets "$COMPLETE_COMPOSE"
+
+echo "$COMPLETE_COMPOSE" | docker stack deploy --compose-file - ${STACK_NAME:-technocore}
